apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petclinic
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: overview-demo/overview-catalog
    kong-manager/service-name: vkpr.spring-petclinic.80                   
    kong-manager/instance: cluster-overview-experience
    grafana/dashboard-selector: "petclinic"
    grafana/alert-label-selector: "alertname=petclinic"    
spec:
  type: service
  lifecycle: experimental
  owner: admin
